[book]
authors = ["kuizhiqing"]
language = "en"
multilingual = false
src = "."
title = "Papers"
description = "Articles through the ages"

[preprocessor.katex]


[output.html]
no-section-label = false
git-repository-url = "https://github.com/kuizhiqing/papers"
site-url = "/"
cname = "papers.kuizhiqing.cn"

[output.html.playground]
editable = false
copy-js = true
line-numbers = false

[output.html.search]
enable = false

[output.html.fold]
enable = true
level = 0

[output.html.redirect]

